### ISSUE TITLE
Export plate to .step file format

### ISSUE THREAD

**Issue by EagleVee** [SeanCline/RabidKeyboard#2]
Hi, I'm new but how can I export the plate file to .step format?

**Comment by SeanCline** [comment]
Oh, that's super easy. With the plate PCB open in Kicad, there's a `File->Export->Step` option in the menu.

![PCBStep](https://user-images.githubusercontent.com/3418587/229211709-fb7e2b85-3f54-4c10-8c6d-79f7e9216b43.gif)

Here's the exported [RabidPlate.step](https://github.com/SeanCline/RabidKeyboard/files/11125292/RabidPlate.zip)

If you're doing something more custom than the RabidKeyboard, you might have better luck starting with http://www.keyboard-layout-editor.com/ and taking the layout to http://builder.swillkb.com/ to generate CAD files of the plate.

**Comment by EagleVee** [comment]
Nice, thank you very much! I haven't used Kicad before so I kinda lost.
